---

image: "archlinux"
packages:
  - "gtk3"
  - "jq"
  - "python-poetry"
  - "wkhtmltopdf"
secrets:
  - "8b542d0f-0a88-4407-8e8f-94a5a2cd8b75"
tasks:
  - test: |
      cd resume-pycli/
      make install
      make test
  - build: |
      cd resume-pycli/
      # skip if not on main branch
      [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ] && complete-build
      make build
  - publish: |
      cd resume-pycli/
      # skip if already published version
      cli_version=$(poetry run resume version)
      pypi_version=$(curl -s https://pypi.org/pypi/resume-pycli/json | jq -r '.releases | keys[]' | sort | tail -n 1)
      [ "$cli_version" == "$pypi_version" ] && complete-build
      make publish
